---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: secure-spring-app-ingress
  namespace: secure-spring-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - secure-spring-app.example.com
    secretName: secure-spring-app-tls
  rules:
  - host: secure-spring-app.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: secure-spring-app-service
            port:
              number: 8080
