---
apiVersion: v1
kind: Service
metadata:
  name: secure-spring-app-service
  namespace: secure-spring-app
  labels:
    app: secure-spring-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30101
      protocol: TCP
      name: http
  selector:
    app: secure-spring-app
