---
apiVersion: v1
kind: Service
metadata:
  name: secure-spring-app-service
  namespace: secure-spring-app
  labels:
    app: secure-spring-app
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: secure-spring-app
---
apiVersion: v1
kind: Service
metadata:
  name: secure-spring-app-lb
  namespace: secure-spring-app
  labels:
    app: secure-spring-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: secure-spring-app
